import "./styles.css";

export const CH_UI_VERSION = "0.2.0";

export {
  tokens,
  palette,
  paletteDark,
  typography,
  spacing,
  radius,
  shadows,
  type ChTokens,
} from "./tokens";
export {
  ChThemeProvider,
  type ChThemeProviderProps,
  type ChThemeMode,
  useChTheme,
  type ChThemeContextValue,
  type ChThemePreference,
  chTheme,
  createChTheme,
} from "./theme";
export {
  AddButton,
  type ChAddButtonProps,
  ApproveButton,
  type ChApproveButtonProps,
  Button,
  type ChButtonProps,
  type ChButtonSize,
  type ChButtonVariant,
  Input,
  type ChInputProps,
  type ChInputSize,
  type ChInputType,
  InputText,
  type ChInputTextProps,
  InputEmail,
  type ChInputEmailProps,
  InputPassword,
  type ChInputPasswordProps,
  PasswordStrength,
  type ChPasswordStrengthProps,
  ShapeBackground,
  type ChShapeBackgroundProps,
  Checkbox,
  type ChCheckboxProps,
  BulletList,
  type ChBulletListItem,
  type ChBulletListProps,
  Feedback,
  type ChFeedbackProps,
  type ChFeedbackSeverity,
  Form,
  type ChFormProps,
  useForm,
  type UseFormParams,
  type UseFormResult,
  Heading,
  type ChHeadingAlign,
  type ChHeadingLevel,
  type ChHeadingProps,
  type ChHeadingSize,
  Icon,
  type ChIconName,
  type ChIconProps,
  type ChIconVariant,
  IconActionButton,
  type ChIconActionButtonProps,
  type ChIconActionButtonVariant,
  Card,
  type ChCardElevation,
  type ChCardProps,
  DescriptionList,
  type ChDescriptionItem,
  type ChDescriptionListProps,
  LanguageSelector,
  Layout,
  type ChLayoutProps,
  Link,
  type ChLinkProps,
  type ChLinkSize,
  type ChLinkColor,
  PageContent,
  type ChPageContentProps,
  PageScaffold,
  type ChPageScaffoldProps,
  Spinner,
  type ChSpinnerProps,
  type ChSpinnerSize,
  Stack,
  type ChStackElement,
  type ChStackGap,
  type ChStackProps,
  ThemeToggle,
  useThemeToggle,
  type UseThemeToggleResult,
  Toggle,
  type ChToggleProps,
  Toast,
  type ChToastProps,
  type ChToastSeverity,
  SidePanel,
  type ChSidePanelProps,
  StatusChip,
  type ChStatusChipProps,
  type ChStatusTone,
  Legend,
  type ChLegendProps,
  type ChLegendEntry,
  type ChLegendStatus,
  Navbar,
  type ChNavbarItem,
  type ChNavbarProps,
  SettingsMenu,
  type ChSettingsMenuProps,
  ConfirmDialog,
  type ChConfirmDialogProps,
  DeleteButton,
  type ChDeleteButtonProps,
  DataTable,
  type ChColumn,
  type ChDataTableProps,
  type ChSortDirection,
  MultiSelect,
  type ChMultiSelectOption,
  type ChMultiSelectProps,
} from "./components";
export {
  ChI18nProvider,
  type ChI18nProviderProps,
  ChI18nContext,
  useTranslation,
  createTranslate,
  apiErrorMessage,
  interpolate,
  type ChI18nContextValue,
  type ChTranslate,
  type ChTranslateVars,
  chBaseMessages,
  chErrorMessages,
  type ChLocale,
  type ChMessages,
  type ChLocaleMessages,
} from "./i18n";
export {
  EMAIL_REGEX,
  NAME_REGEX,
  PASSWORD_MIN_LENGTH,
  PASSWORD_UPPERCASE_REGEX,
  PASSWORD_LOWERCASE_REGEX,
  PASSWORD_DIGIT_REGEX,
  PASSWORD_SPECIAL_REGEX,
  PASSWORD_CRITERIA,
  type ChPasswordCriterion,
  type ChPasswordCriterionId,
  type ChPasswordCriterionState,
  passwordCriteriaState,
  passwordStrength,
  isValidEmail,
  isValidName,
  isValidPassword,
} from "./validation";
