import "./styles.css";

export const CH_UI_VERSION = "0.2.0";

export {
  tokens,
  palette,
  paletteDark,
  typography,
  spacing,
  radius,
  shadows,
  type ChTokens,
} from "./tokens";
export {
  ChThemeProvider,
  type ChThemeProviderProps,
  type ChThemeMode,
  useChTheme,
  type ChThemeContextValue,
  type ChThemePreference,
  chTheme,
  createChTheme,
} from "./theme";
export {
  Button,
  type ChButtonProps,
  type ChButtonSize,
  type ChButtonVariant,
  Input,
  type ChInputProps,
  type ChInputSize,
  type ChInputType,
  InputText,
  type ChInputTextProps,
  InputEmail,
  type ChInputEmailProps,
  InputPassword,
  type ChInputPasswordProps,
  Feedback,
  type ChFeedbackProps,
  type ChFeedbackSeverity,
  Form,
  type ChFormProps,
  useForm,
  type UseFormParams,
  type UseFormResult,
  Heading,
  type ChHeadingAlign,
  type ChHeadingLevel,
  type ChHeadingProps,
  type ChHeadingSize,
  Icon,
  type ChIconName,
  type ChIconProps,
  type ChIconVariant,
  Card,
  type ChCardElevation,
  type ChCardProps,
  DescriptionList,
  type ChDescriptionItem,
  type ChDescriptionListProps,
  LanguageSelector,
  Layout,
  type ChLayoutProps,
  Link,
  type ChLinkProps,
  type ChLinkSize,
  PageContent,
  type ChPageContentProps,
  PageScaffold,
  type ChPageScaffoldProps,
  Spinner,
  type ChSpinnerProps,
  type ChSpinnerSize,
  Stack,
  type ChStackElement,
  type ChStackGap,
  type ChStackProps,
  ThemeToggle,
  useThemeToggle,
  type UseThemeToggleResult,
  StatusChip,
  type ChStatusChipProps,
  type ChStatusTone,
  ConfirmDialog,
  type ChConfirmDialogProps,
  DataTable,
  type ChColumn,
  type ChDataTableProps,
  type ChSortDirection,
  MultiSelect,
  type ChMultiSelectOption,
  type ChMultiSelectProps,
} from "./components";
export {
  ChI18nProvider,
  type ChI18nProviderProps,
  ChI18nContext,
  useTranslation,
  createTranslate,
  interpolate,
  type ChI18nContextValue,
  type ChTranslate,
  type ChTranslateVars,
  chBaseMessages,
  type ChLocale,
  type ChMessages,
  type ChLocaleMessages,
} from "./i18n";
export {
  EMAIL_REGEX,
  PASSWORD_MIN_LENGTH,
  isValidEmail,
  isValidPassword,
} from "./validation";
